name: eclipsed_by_you Instagram Post

on:
  schedule:
    - cron: '30 0 * * *'   # 06:00 AM IST
    - cron: '0 3 * * *'    # 08:30 AM IST
    - cron: '0 7 * * *'    # 12:30 PM IST
    - cron: '30 9 * * *'   # 03:00 PM IST
    - cron: '30 11 * * *'  # 05:00 PM IST
    - cron: '0 13 * * *'   # 06:30 PM IST
    - cron: '30 15 * * *'  # 09:00 PM IST
    - cron: '0 17 * * *'   # 10:30 PM IST
  workflow_dispatch:        # allows manual trigger via GitHub UI

jobs:
  post_to_instagram:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      IG_ECLIPSED_BY_YOU_TOKEN: ${{ secrets.IG_ECLIPSED_BY_YOU_TOKEN }}
      IG_ECLIPSED_BY_YOU_ID: ${{ secrets.IG_ECLIPSED_BY_YOU_ID }}
      DROPBOX_ECLIPSED_BY_YOU_APP_KEY: ${{ secrets.DROPBOX_ECLIPSED_BY_YOU_APP_KEY }}
      DROPBOX_ECLIPSED_BY_YOU_APP_SECRET: ${{ secrets.DROPBOX_ECLIPSED_BY_YOU_APP_SECRET }}
      DROPBOX_ECLIPSED_BY_YOU_REFRESH: ${{ secrets.DROPBOX_ECLIPSED_BY_YOU_REFRESH }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install Dependencies
        run: |
          pip install --upgrade pip
          pip install dropbox requests python-telegram-bot==13.15 pytz pynacl

      - name: 🚀 Run Instagram Uploader
        run: python eclipsed_by_you_post.py
